### ISSUE TITLE
Meme Slide

### ISSUE THREAD

**Issue by potatoyenn** [CS-DictionaryTeam/switch#33]
Does anyone have a solution to get rid of the white space between the images? Should we resize the photo? Leave it as is?

Are the memes taking up too much space of this layout? Should I resize it?

![screen shot 2017-04-26 at 3 14 12 pm](https://cloud.githubusercontent.com/assets/20568980/25459763/b59a4ea0-2a94-11e7-85a1-ffd54cc84e14.png)
![screen shot 2017-04-26 at 3 14 23 pm](https://cloud.githubusercontent.com/assets/20568980/25459764/b5a17068-2a94-11e7-99b6-c374b506bd0b.png)

**Comment by RobertoAF** [comment]
Wow, it looks amazing! 

Do you know approximately how much space they currently take up? I wonder what it would look like if you made them smaller, say 33% instead of 50% of the screen size? 

To me, the white space doesn't look bad. The only thing is that without cursor arrows, I wouldn't know that I could swipe them. Would it be possible to add those somehow on the right and left-hand sides?

**Comment by RobertoAF** [comment]
Update:
Changed the layout height of the meme carousel so that it didn't appear stretched.
Also, changed the padding between the image and text to accommodate the longer definitions.

<img width="507" alt="screen shot 2017-05-03 at 11 19 39 pm" src="https://cloud.githubusercontent.com/assets/13029161/25697158/b29bb6e6-306e-11e7-9c32-3b5a0a90b4d3.png">

<img width="412" alt="screen shot 2017-05-04 at 2 07 08 am" src="https://cloud.githubusercontent.com/assets/13029161/25697149/a648de46-306e-11e7-9135-3e6cbabee3de.png">

**Comment by RobertoAF** [comment]
Are all of the memes displaying correctly? For example, I don't see the Grace Hopper meme.
